name = "MGSR"
prefix = "mgsr"

[properties]
author = "Rebel"
url = "https://github.com/rebelvg"

[files]
include = [
    "mod.cpp",
    "mod.paa",
]
exclude = [
  "README.md",
  "mklink.js"
]

[version]
major = 0
minor = 4
patch = 9
build = 0

[hemtt.build]
pdrive = "require"
